#!/bin/sh

echo "Content-Type: text/plain;charset=UTF-8"
echo 

. "$(dirname "$0")/environment" 2>&1

if [ "$allow_www_bzr_revert" = "" ] || [ "$allow_www_bzr_revert" = "0" ]; then
    echo "*** Www Bazaar revert is not allowed ***"
    
    exit
fi

export HOME
export PATH
export PYTHONPATH

echo "*** BEGIN ***"

(cd "$(dirname "$0")/../"; nice -n 25 bzr revert) 2>&1

echo "*** END ***"

true

