#!/usr/bin/env bash

echo "Content-Type: text/plain;charset=utf-8"
echo 

. "$(dirname "$0")/environment.conf" 2>&1

if [ $[allow_www_git_hard_reset] = 0 ]
then
    echo "*** Www Git Hard Reset is not allowed ***"
    
    exit 1
fi

if [ "$www_git_key" = "" ] || [ "$PATH_INFO" != "/key/$www_git_key" ]
then
    echo "*** Invalid Www Git Key ***"
    
    exit 1
fi

echo "*** BEGIN ***"

(cd "$(dirname "$0")/../"; nice -n 25 git reset --hard) 2>&1

echo "*** END ***"

true

