#!/bin/sh

echo "Content-Type: text/plain;charset=utf-8"
echo 

. "$(dirname "$0")/environment.conf" 2>&1

if [ $[allow_www_git_status] = 0 ]
then
    echo "*** Www Git Status is not allowed ***"
    
    exit
fi

if [ "$www_git_key" = "" ] || [ "$PATH_INFO" != "/key/$www_git_key" ]
then
    echo "*** Invalid Www Git Key ***"
    
    exit
fi

echo "*** BEGIN ***"

(cd "$(dirname "$0")/../"; nice -n 25 git status) 2>&1

echo "*** END ***"

true

