#!/bin/sh

. "$(dirname "$0")/environment"
export HOME
export PATH
export PYTHONPATH

echo "Content-Type: text/plain;charset=UTF-8"
echo

echo "*** BEGIN ***"

(cd "$(dirname "$0")/../"; nice -n 25 bzr update) 2>&1

echo "*** END ***"

true

